### ISSUE TITLE
Could not resolve host: ims-na1.adobelogin.com

### ISSUE THREAD

**Issue by nioniofr** [benrwoodard/adobeanalyticsr#155]
Dear All,
I'm having trouble getting API (with jwt) access when I'm using the network at work (company firewall). 
So I have to declare a new network stream to access the data adobe. Do you know what ip addresses (ports) 
need to be declared or how to check what ip (port) is used?
I sincerely thank you for your help,

P.S. I declared the ims-na1.adobelogin.com but it didn't solve my problem.

**Comment by charlie-gallagher** [comment]
This is a new problem for me, firewalls and DNS are a little outside my zone of experience (I suggest asking Adobe). But here's the result of `dig ims-na1.adobelogin.com` in case that helps? Apologies if this is totally off base. It currently resolves to the IP address 3.227.15.71

```
$ dig ims-na1.adobelogin.com

; <<>> DiG 9.10.6 <<>> ims-na1.adobelogin.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8497
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;ims-na1.adobelogin.com.		IN	A

;; ANSWER SECTION:
ims-na1.adobelogin.com.	60	IN	CNAME	adobelogin.prod.ims.adobejanus.com.
adobelogin.prod.ims.adobejanus.com. 60 IN CNAME	edgeproxy-va6.cloud.adobe.io.
edgeproxy-va6.cloud.adobe.io. 45 IN	CNAME	ethos.ethos02-prod-va6.ethos.adobe.net.
ethos.ethos02-prod-va6.ethos.adobe.net.	56 IN CNAME pv2ys4tjt9x.prod.cloud.adobe.io.
pv2ys4tjt9x.prod.cloud.adobe.io. 56 IN	A	3.227.15.71

;; Query time: 61 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Feb 16 08:21:35 EST 2023
;; MSG SIZE  rcvd: 237
```

I will agree that that's the only hostname we send a request to. And since it's over HTTPS, it would be [port 443](https://en.wikipedia.org/wiki/HTTPS#Technical).

**Comment by benrwoodard** [comment]
@nioniofr were you able to get this working?

**Comment by nioniofr** [comment]
Hello,

Sorry for the delay. Last Friday I spent half a day with my security team (lol). We solved the problem after declaring:
ims-na1.adobelogin.com and port 443.

Regards,
