### ISSUE TITLE
Support metric level segmentation

### ISSUE THREAD

**Issue by benrwoodard** [benrwoodard/adobeanalyticsr#23]
When comparing metrics across segments it would be good to be able to segment on the metric itself so you can pull different results for each metric.

![image](https://user-images.githubusercontent.com/2105463/98995667-a8ab6f80-24ff-11eb-9711-f8cc9cb39917.png)

**Comment by charlie-gallagher** [comment]
On a surface level, this is straightforward to support. But is it necessary, since users can get this behavior already with several separate queries? 

What would be an intuitive way to do this? The obvious choice is to add a `metricSegmentId` argument, which is a vector or list of vectors the same length as `metrics`. So,

```r
aw_freeform_table(
  metrics = c("met1", "met2", "met3"),
  metricSegmentId = list(NA, "s1234567890", c("s1234567890", "s0987654321"))
)
```

The result here would be a breakdown report, per usual, but `met2` would be restricted to `s1234567890`, and `met3` would be restricted to both `s1234567890` and `s0987654321`. 

Pros:

- If someone wants the same metric for three different segments, this would be a fast way to request it (instead of 3 separate queries with their own global segments)

Cons:

- Another argument to manage, more complicated management of the metric container functions
- The functionality is already available, through multiple individual queries
- I'm not sure how the metric columns should be named on output
  - How should `prettynames` treat this? 
  - How should it be treated in general? Workspace benefits from multiple column headers, we would probably end up with very long names (segment ID? Ugly)

**Comment by charlie-gallagher** [comment]
Since this is less useful than #27, I'm going to close this in favor of that
