### ISSUE TITLE
Getting to an Error page after inputing aw_token()

### ISSUE THREAD

**Issue by matt-cheng** [benrwoodard/adobeanalyticsr#92]
I get to an Adobe error page after I get to Step 3 on https://adobeanalyticsr.com/#3-get-your-authorization-token. 

Error
There was an error with this action. Try again later.

**Comment by benrwoodard** [comment]
This is usually because the `AW_CLIENT_ID` and `AW_CLIENT_SECRET` were not added to the .Renviron file, they were not copied and pasted accurately, or after adding these variables to the .Renviron file you did not restart your R session. 
![image](https://user-images.githubusercontent.com/2105463/112076995-e4131600-8b51-11eb-8551-6a718dd14429.png)
Have you checked all of these yet?  If so and the error persists, can you share with me the screenshot of the error?
